version: "3.7"

services:
  app:
    image: node:14.17.2
    command: bash -c "npm install && npm run dev"
    ports:
      - 3031:3031
    working_dir: /hitzii_backend
    volumes:
      - ./:/hitzii_backend

  redis:
    image: redis:5
    ports:
      - 6379:6379
