version: "3"

services:
  app:
    build:
        context: .
        dockerfile: ./Dockerfile
    depends_on:
      - redis
    environment:
      test: null
    ports :
      -  7474:3031
  redis:
    image: redis:5
    ports:
      - 6379:6379
